@startuml

!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

title ER диаграмма подсистемы управления командировками
caption Диаграмма объектов

package НСИ<<folder>> {

 _Справочник(Организация, "Организации")
 _Справочник(Сотрудник, "Сотрудники")
 _Справочник(Контрагент, "Контрагенты")
 _Справочник(Гостиница, "Гостиницы")


}

package УправлениеКомандировками <<folder>> {

     _Перечисление(СтатусыЗаявкиНаКомандировку, "Статус заявки на командировку"){
        Новая
        СогласованаСотрудником
        СогласованаРуководителем
        ОтклоненаРуководителем
        ПеренесенаРуководителем
        СогласованаОтделомКадров
        ОтклоненаОтделомКадров
      }

      _Документ(ПланированиеКомандировок, "План командировок") {
        Организация
        -- Сотрудники--
        Сотрудник
        ДатаНачала
        ДатаОкончания
        Контрагент
        Адрес
        Цель
        ПланируемыйРезультат
        Бюджет
    }

      _Документ(ЗаявкаНаКомандировку, "Заявка на командировку") {
        Организация
        Основание
        Сотрудник
        ДатаНачала
        ДатаОкончания
        Контрагент
        Цель
        ПланируемыйРезультат
        Адрес
        Перевозчик
        Рейс
        СтоимостьПеревозки
        Гостиница
        СтоимостьПроживания
        Бюджет
        Статус
    }

   _РегистрСведений(СогласованиеКомандировок, "Согласование командировок") {
        <$d> Организация
        <$d> Сотрудник
        <$d> ДатаНачала
        <$d> ДатаОкончания
        <$d> Контрагент
        <$d> Цель
        <$r> Статус
}

СтатусыЗаявкиНаКомандировку--> ЗаявкаНаКомандировку::Статус
Организация--> ЗаявкаНаКомандировку::Организация
Организация--> ПланированиеКомандировок::Организация
ПланированиеКомандировок--> ЗаявкаНаКомандировку::Основание
Сотрудник--> ПланированиеКомандировок::Сотрудник
Сотрудник--> ЗаявкаНаКомандировку::Сотрудник
Контрагент--> ПланированиеКомандировок::Контрагент
Контрагент--> ЗаявкаНаКомандировку::Перевозчик
Контрагент--> ЗаявкаНаКомандировку::Контрагент
Гостиница--> ЗаявкаНаКомандировку::Гостиница
СтатусыЗаявкиНаКомандировку--> СогласованиеКомандировок::Статус
Контрагент--> СогласованиеКомандировок::Контрагент
Организация--> СогласованиеКомандировок::Организация
Сотрудник--> СогласованиеКомандировок::Сотрудник

ЗаявкаНаКомандировку--> СогласованиеКомандировок
ПланированиеКомандировок--> СогласованиеКомандировок
@enduml